// Shared branded HTML shell for app-triggered transactional emails (vehicle
// inquiries, etc.) — NOT Supabase Auth's own emails (those are static files
// under supabase/templates/, generated by scripts/generate-email-templates.mjs
// and rendered by GoTrue). Mirrors that script's shell() layout/structure
// (logo, "Powered by Arresa" eyebrow, serif heading, footer links) so every
// email the app sends looks like one product, but uses the CURRENT brand
// color (#007f77, matching globals.css since PR #36's visual-fidelity
// pass) rather than that script's older, now-stale #0e6b73.
import { publicEnv } from "@/lib/env";

const BRAND = "#007f77";
const BRAND_DARK = "#005f5a";
const INK = "#0d1117";
const MUTED = "#6b7280";
const BORDER = "#e5e7eb";

export interface EmailShellOptions {
  preheader: string;
  heading: string;
  bodyHtml: string;
  ctaLabel?: string;
  ctaUrl?: string;
  footnote?: string;
}

export function renderEmailShell({ preheader, heading, bodyHtml, ctaLabel, ctaUrl, footnote }: EmailShellOptions): string {
  const siteUrl = publicEnv.NEXT_PUBLIC_SITE_URL;

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>HarakaGari</title>
  </head>
  <body style="margin:0; padding:0; background-color:#f5f5f4; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
    <span style="display:none; font-size:1px; color:#f5f5f4; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden;">
      ${preheader}
    </span>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f4; padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px; background-color:#ffffff; border-radius:12px; overflow:hidden; border:1px solid ${BORDER};">
            <tr>
              <td style="padding:28px 32px 20px 32px; border-bottom:1px solid ${BORDER};">
                <img src="${siteUrl}/logo.png" alt="HarakaGari" height="28" style="height:28px; display:block;" />
                <div style="margin-top:6px; font-size:11px; letter-spacing:0.06em; color:${MUTED}; text-transform:uppercase;">
                  Powered by Arresa
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:32px;">
                <h1 style="margin:0 0 12px 0; font-family:Georgia,'Times New Roman',serif; font-size:22px; font-weight:600; color:${INK};">
                  ${heading}
                </h1>
                <div style="font-size:14px; line-height:1.6; color:#374151;">
                  ${bodyHtml}
                </div>
                ${
                  ctaLabel && ctaUrl
                    ? `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:24px 0 8px 0;">
                  <tr>
                    <td style="border-radius:8px; background-color:${BRAND};">
                      <a href="${ctaUrl}" style="display:inline-block; padding:12px 24px; font-size:14px; font-weight:600; color:#ffffff; text-decoration:none; border-radius:8px;">
                        ${ctaLabel}
                      </a>
                    </td>
                  </tr>
                </table>`
                    : ""
                }
                ${
                  footnote
                    ? `<p style="margin:24px 0 0 0; font-size:12px; line-height:1.6; color:${MUTED};">
                  ${footnote}
                </p>`
                    : ""
                }
              </td>
            </tr>
            <tr>
              <td style="padding:20px 32px; background-color:#fafaf9; border-top:1px solid ${BORDER};">
                <p style="margin:0; font-size:12px; color:${MUTED};">
                  <a href="${siteUrl}/terms" style="color:${BRAND_DARK}; text-decoration:underline;">Terms of Service</a>
                  &nbsp;·&nbsp;
                  <a href="${siteUrl}/privacy" style="color:${BRAND_DARK}; text-decoration:underline;">Privacy Policy</a>
                </p>
                <p style="margin:8px 0 0 0; font-size:12px; color:${MUTED};">
                  © HarakaGari by Arresa. All rights reserved.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

export interface InquiryEmailData {
  vehicleTitle: string;
  vehicleUrl: string;
  vehiclePrice: string;
  showroomName: string;
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  message: string;
}

/** Sent to the showroom owner and to every admin — same content either way. */
export function renderInquiryNotificationEmail(data: InquiryEmailData): { subject: string; html: string } {
  const subject = `New inquiry: ${data.vehicleTitle} — HarakaGari`;
  const html = renderEmailShell({
    preheader: `${data.contactName} is interested in ${data.vehicleTitle}`,
    heading: "New Vehicle Inquiry",
    bodyHtml: `
      <p style="margin:0 0 16px 0;">A customer sent an inquiry about a listing on <strong>${escapeHtml(data.showroomName)}</strong>.</p>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 16px 0; border:1px solid ${BORDER}; border-radius:8px;">
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Vehicle</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.vehicleTitle)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Price</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.vehiclePrice)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Name</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.contactName)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Email</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.contactEmail)}</td></tr>
        <tr><td style="padding:12px 16px; font-size:13px; color:${MUTED};">Phone</td><td style="padding:12px 16px; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.contactPhone)}</td></tr>
      </table>
      <p style="margin:0 0 4px 0; font-size:13px; color:${MUTED};">Message</p>
      <p style="margin:0; padding:12px 16px; background-color:#f8f9fa; border-radius:8px; white-space:pre-line;">${escapeHtml(data.message)}</p>
    `,
    ctaLabel: "View Listing",
    ctaUrl: data.vehicleUrl,
    footnote: "Reply directly to the customer's email or phone above — this inbox does not accept replies.",
  });
  return { subject, html };
}

/** Sent to the customer who submitted the inquiry. */
export function renderInquiryThankYouEmail(data: InquiryEmailData): { subject: string; html: string } {
  const subject = `We've received your inquiry — ${data.vehicleTitle}`;
  const html = renderEmailShell({
    preheader: `Thanks for your interest in ${data.vehicleTitle} — ${data.showroomName} will be in touch.`,
    heading: "Thanks for your inquiry",
    bodyHtml: `
      <p style="margin:0 0 12px 0;">Hi ${escapeHtml(data.contactName)},</p>
      <p style="margin:0 0 16px 0;">Your inquiry about the <strong>${escapeHtml(data.vehicleTitle)}</strong> listed by <strong>${escapeHtml(data.showroomName)}</strong> has been sent. They'll reach out to you directly at ${escapeHtml(data.contactEmail)} or ${escapeHtml(data.contactPhone)}.</p>
      <p style="margin:0 0 4px 0; font-size:13px; color:${MUTED};">Your message</p>
      <p style="margin:0; padding:12px 16px; background-color:#f8f9fa; border-radius:8px; white-space:pre-line;">${escapeHtml(data.message)}</p>
    `,
    ctaLabel: "View Listing",
    ctaUrl: data.vehicleUrl,
    footnote: "If you didn't send this inquiry, you can safely ignore this email.",
  });
  return { subject, html };
}

export interface FinancingApplicationEmailData {
  vehicleTitle: string;
  vehicleUrl: string;
  showroomName: string;
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  employmentStatusLabel: string;
  monthlyIncome: string;
  desiredDownPayment: string;
  desiredTenureMonths: number;
}

/** Sent to the showroom owner and to every admin — same content either way. */
export function renderFinancingApplicationNotificationEmail(data: FinancingApplicationEmailData): { subject: string; html: string } {
  const subject = `New financing application: ${data.vehicleTitle} — HarakaGari`;
  const html = renderEmailShell({
    preheader: `${escapeHtml(data.contactName)} applied for financing on ${escapeHtml(data.vehicleTitle)}`,
    heading: "New Financing Application",
    bodyHtml: `
      <p style="margin:0 0 16px 0;">A customer applied for financing on a listing on <strong>${escapeHtml(data.showroomName)}</strong>.</p>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 16px 0; border:1px solid ${BORDER}; border-radius:8px;">
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Vehicle</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.vehicleTitle)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Name</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.contactName)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Email</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.contactEmail)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Phone</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.contactPhone)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Employment</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.employmentStatusLabel)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Monthly income</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.monthlyIncome)}</td></tr>
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Desired down payment</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.desiredDownPayment)}</td></tr>
        <tr><td style="padding:12px 16px; font-size:13px; color:${MUTED};">Desired loan term</td><td style="padding:12px 16px; font-size:13px; font-weight:600; text-align:right;">${data.desiredTenureMonths} months</td></tr>
      </table>
    `,
    ctaLabel: "View Listing",
    ctaUrl: data.vehicleUrl,
    footnote: "Reply directly to the customer's email or phone above — this inbox does not accept replies.",
  });
  return { subject, html };
}

/** Sent to the customer who submitted the financing application. */
export function renderFinancingApplicationReceivedEmail(data: FinancingApplicationEmailData): { subject: string; html: string } {
  const subject = `We've received your financing application — ${data.vehicleTitle}`;
  const html = renderEmailShell({
    preheader: `Thanks for applying for financing on ${escapeHtml(data.vehicleTitle)} — ${escapeHtml(data.showroomName)} will be in touch.`,
    heading: "Financing Application Received",
    bodyHtml: `
      <p style="margin:0 0 12px 0;">Hi ${escapeHtml(data.contactName)},</p>
      <p style="margin:0;">Your financing application for the <strong>${escapeHtml(data.vehicleTitle)}</strong> listed by <strong>${escapeHtml(data.showroomName)}</strong> has been sent. They'll review it and reach out to you directly at ${escapeHtml(data.contactEmail)} or ${escapeHtml(data.contactPhone)} within 24 hours.</p>
    `,
    ctaLabel: "View Listing",
    ctaUrl: data.vehicleUrl,
    footnote: "If you didn't submit this application, you can safely ignore this email.",
  });
  return { subject, html };
}

export interface ShowroomRegistrationEmailData {
  businessName: string;
  ownerFullName: string;
}

/** Sent to every admin when a new showroom application is submitted. */
export function renderShowroomRegistrationAdminNotificationEmail(
  data: ShowroomRegistrationEmailData & { reviewUrl: string },
): { subject: string; html: string } {
  const subject = `New showroom application: ${data.businessName} — HarakaGari Admin`;
  const html = renderEmailShell({
    preheader: `${data.ownerFullName} applied to list ${data.businessName} on HarakaGari.`,
    heading: "New Showroom Application",
    bodyHtml: `
      <p style="margin:0 0 16px 0;">A new showroom application is awaiting review.</p>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0; border:1px solid ${BORDER}; border-radius:8px;">
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Business</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.businessName)}</td></tr>
        <tr><td style="padding:12px 16px; font-size:13px; color:${MUTED};">Owner</td><td style="padding:12px 16px; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.ownerFullName)}</td></tr>
      </table>
    `,
    ctaLabel: "Review in Admin Panel",
    ctaUrl: data.reviewUrl,
    footnote: "Review the submitted documents and approve or reject the application from the admin panel.",
  });
  return { subject, html };
}

/** Sent to the applicant confirming their submission was received. */
export function renderShowroomRegistrationReceivedEmail(data: ShowroomRegistrationEmailData): { subject: string; html: string } {
  const subject = `We've received your showroom application — HarakaGari`;
  const html = renderEmailShell({
    preheader: `Your application for ${data.businessName} is being reviewed.`,
    heading: "Application Received",
    bodyHtml: `
      <p style="margin:0 0 12px 0;">Hi ${escapeHtml(data.ownerFullName)},</p>
      <p style="margin:0;">Thanks for applying to list <strong>${escapeHtml(data.businessName)}</strong> on HarakaGari. We're reviewing your business information and documents, and will be in touch within 1–2 business days.</p>
    `,
    footnote: "If you didn't submit this application, please contact support.",
  });
  return { subject, html };
}

export interface SubscriptionReminderEmailData {
  showroomName: string;
  endDate: string; // "YYYY-MM-DD"
  urgency: "EXPIRING_SOON" | "OVERDUE";
}

/** Sent to every admin — once per subscription period, see reminder_sent_at. */
export function renderSubscriptionReminderEmail(data: SubscriptionReminderEmailData): { subject: string; html: string } {
  const formattedDate = new Date(`${data.endDate}T00:00:00`).toLocaleDateString("en-KE", { year: "numeric", month: "long", day: "numeric" });
  const isOverdue = data.urgency === "OVERDUE";
  const subject = isOverdue
    ? `Subscription overdue: ${data.showroomName} — HarakaGari Admin`
    : `Subscription expiring soon: ${data.showroomName} — HarakaGari Admin`;
  const html = renderEmailShell({
    preheader: isOverdue
      ? `${data.showroomName}'s subscription ended on ${formattedDate}.`
      : `${data.showroomName}'s subscription ends on ${formattedDate}.`,
    heading: isOverdue ? "Showroom Subscription Overdue" : "Showroom Subscription Expiring Soon",
    bodyHtml: `
      <p style="margin:0 0 12px 0;">
        ${isOverdue ? "This showroom's subscription period has already ended." : "This showroom's subscription period is ending soon."}
      </p>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0; border:1px solid ${BORDER}; border-radius:8px;">
        <tr><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; color:${MUTED};">Showroom</td><td style="padding:12px 16px; border-bottom:1px solid ${BORDER}; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(data.showroomName)}</td></tr>
        <tr><td style="padding:12px 16px; font-size:13px; color:${MUTED};">${isOverdue ? "Ended on" : "Ends on"}</td><td style="padding:12px 16px; font-size:13px; font-weight:600; text-align:right;">${escapeHtml(formattedDate)}</td></tr>
      </table>
    `,
    ctaLabel: "Review in Admin Panel",
    ctaUrl: `${publicEnv.NEXT_PUBLIC_SITE_URL}/admin/payments`,
    footnote: "Record a new payment for this showroom to renew its subscription period.",
  });
  return { subject, html };
}
